=== Quantum-Science-and-Technology-Lab/labber-wrapper/json_schemas/1D_&_2Dsweep.json
{
    "$id": "json_schemas/1D_&_2Dsweep.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title" : "1D & 2D sweep values",
    "required" : [
        "fast_ch",
        "bias_v",
        "plunger_v",
        "acc_v",
        "vb1_v",
        "vb2_v",
        "fast_vstart",
        "fast_vend",
        "fast_steps",
        "fast_step_size",
        "fast_ch_name"
    ],
    "type": "object",
    "properties": {
        "slow_ch": {
            "type": "array"
        },
        "fast_ch": {
            "type": "array"
        },
        "bias_v": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "plunger_v": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "acc_v": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "vb1_v": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "vb2_v": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5    
        },
        "fast_vstart": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "fast_vend": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "fast_steps": {
            "type": "number"
        },
        "fast_step_size": {
            "type": "number"
        },
        "fast_ch_name": {
            "type": "string"
        },
        "slow_vstart": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "slow_vend": {
            "type": "number",
            "minimum": -2.5,
            "maximum": 2.5
        },
        "slow_steps": {
            "type": "number"
        },
        "slow_step_size": {
            "type": "number"
        },
        "slow_ch_name": {
            "type": "string"
        }   
    }
}

=== Quantum-Science-and-Technology-Lab/labber-wrapper/configs/2D_sweep.json
{
    "slow_ch": [2],
    "fast_ch": [3],
    "bias_v": 0,
    "plunger_v": 0,
    "acc_v": 0,
    "vb1_v": 0,
    "vb2_v": 0,
    "slow_vstart": 0,
    "slow_vend": -1.805,
    "slow_steps": 2,
    "slow_step_size": 2.05,
    "fast_vstart": 0,
    "fast_vend": -0.5,
    "fast_steps": 41,
    "fast_step_size": 0.05,
    "fast_ch_name": "Vx",
    "slow_ch_name": "Vy"
}
